import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./css/globals.css";
import Header from "./components/Header"
import Footer from "./components/Footer"
import Banner from "./components/Banner";
import Link from "next/link";

import   "./css/menu.css" 
import   "./css/footer.css"  
import   "./css/home.css"   

const geistSans = Geist({  
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = { 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (


<html lang="en">
    <link rel="shortcut icon" href="./logo.jpg" type="image/x-icon" />
    <body  > 
      
         <Header />
         
          <main >
          
          {children}
            
          </main>        
        <Footer />







 

</body>
</html>

  );
}
